apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: tcb-vote-back
spec: # bloco aonde vamos configurar o pod tcb - um banco de dados em memoria do kubernetes
  replicas: 1
  selector:
    matchLabels:
      app: tcb-vote-back
  template:
    metadata:
      labels:
        app: tcb-vote-back
    spec:
      containers:
      - name: tcb-vote-back
        image: thecloudbootcamp/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: tcb-vote-back
spec: # configurando a porta para que a parte do front consiga acessar o bd temporario
  ports:
  - port: 6379
  selector:
    app: tcb-vote-back
--- # parte que vai subir o pod tcb-vote-front 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcb-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcb-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: tcb-vote-front
    spec:
      containers:
      - name: tcb-vote-front
        image: gcr.io/<PROJECT_ID>/tcb-vote-front:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "tcb-vote-back"
--- # configurando um ip publico para acessar a aplicação
apiVersion: v1
kind: Service
metadata:
  name: tcb-vote-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tcb-vote-front
